#!/bin/sh -e
# usage:
#   scripts/burn ISO_URL PATH_DISK

ISO_IMAGE_URL=${1}
PATH_DISK=${2:-/dev/disk2}

curl -L "$ISO_IMAGE_URL" -o rpi.zip
unzip rpi.zip

# sudo dd if=nixos-sd-image-23.05.20230320.8276a16-aarch64-linux.img of="${PATH_DISK}" bs=1m
